### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by ShayBox**
Remove redundant -get from apt command
Change kotlin to use snap
Merge duplicated install commands
Use current WORKDIR instead of hard paths

### CODE REVIEW

**Comment by SebastiaanYN** [comment]
Thanks for the PR, there are however a couple of issues.

First of all, the change regarding the C#/.NET compiler don't function, instead of grouping the `apt-transport-https` and `dotnet-sdk-2.2` install it should stay like this.
```dockerfile
RUN apt install -y apt-transport-https
RUN apt update
RUN apt install -y dotnet-sdk-2.2
```

The Kotlin installation also doesn't work due to an issue with snap.
```
Step 26/40 : RUN snap install kotlin
 ---> Running in 36e9b5f18a86
/bin/sh: 1: snap: not found
The command '/bin/sh -c snap install kotlin' returned a non-zero code: 127
```

**Comment by SebastiaanYN** [comment]
The kotlin installation still provides an error.
```
Step 26/40 : RUN snap install kotlin
 ---> Running in 134966189bff
error: cannot communicate with server: Post http://localhost/v2/snaps/kotlin: dial unix /run/snapd.socket: connect: no such file or directory
The command '/bin/sh -c snap install kotlin' returned a non-zero code: 1
```

**Comment by SebastiaanYN** [comment]
snapd doesn't start through service.
```
Step 5/41 : RUN service snapd start
 ---> Running in 9d04a5ffb95a
snapd: unrecognized service
```
It also seems like getting snapd to run inside a docker container requires more work than you'd want. Several sources point to https://github.com/ogra1/snapd-docker as an example of getting snap working inside docker containers.

**Comment by ShayBox** [comment]
I'll just fix kotlin when I make another PR to switch it to alpine

**Pull request merged**
